name: Build and Publish Docs

on:
  push:
    branches-ignore:
      - '*'
    tags:
      - 'v*'

permissions:
  contents: write   # to read and write repository contents
  pages: write      # to deploy to Pages
  id-token: write   # to verify the deployment originates from an appropriate source

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Source Code'
        id: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build Docs
        id: build
        run: make build-static-site

      - name: Upload artifact for deployment
        id: upload-pages
        uses: actions/upload-pages-artifact@v4
        with:
          path: 'build/'

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

