name: Build and Publish Docs

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Source Code'
        id: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build Docs
        id: build
        run: make build-static-site
        with:
          source: ./build
          destination: ./build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './build'

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write   # to read and write repository contents
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

