name: Trigger API Docs Update Workflow

on:
  workflow_call:
    inputs:
      api-name:
        required: true
        type: string
      api-version:
        required: true
        type: string
      api-spec-url:
        required: true
        type: string
    secrets:
      token:
        required: true

jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Workflow in Another Repository
        run: |
          # Set the required variables
          event_type="trigger-workflow" 
          apiName=${{ github.event.inputs.api_name }}"
          apiVersion="${{ github.event.inputs.api_version }}"
          apiSpecUrl="${{ github.event.inputs.api_spec_url }}"
          
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.token }} \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/racastellanosm/playground-openapi-to-github-pages/dispatches \
            -d "{\"event_type\": \"new-api-version-tagged\", \"client_payload\": {\"apiName\": \"$apiName\", \"version\": \"$apiVersion\", \"apiSpecUrl\": \"$apiSpecUrl\"}}"